name: github-runner

networks:
  github-runner:
    name: github-runner

volumes:
  github-runner-data:
    name: github-runner-data

services:
  github-runner:
    image: myoung34/github-runner:2.335.1-ubuntu-noble@sha256:e2e1ff7077ffa67986a5db7dd61b473cc3b0f661a6db8bfee41cb59eb9aab4d1
    container_name: github-runner
    restart: unless-stopped
    networks:
      - github-runner
    environment:
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_GROUP=Self-Hosted
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - CONFIGURED_ACTIONS_RUNNER_FILES_DIR=/runner/data
      - DISABLE_AUTOMATIC_DEREGISTRATION=true
      - RUNNER_SCOPE=org
      - ORG_NAME=binary-braids
      - RUN_AS_ROOT=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github-runner-data:/runner/data
      - /tmp/runner:/tmp/runner
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro