name: github-runner

networks:
  github-runner:
    name: github-runner

volumes:
  github-runner-data:
    name: github-runner-data

services:
  github-runner:
    image: myoung34/github-runner:2.332.0-ubuntu-noble@sha256:dfb5c11cc9ca3b153786ce65d35a9642e71bda0bc8851283e9d805eb471cc8df
    container_name: github-runner
    restart: unless-stopped
    networks:
      - github-runner
    environment:
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_GROUP=Self-Hosted
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - CONFIGURED_ACTIONS_RUNNER_FILES_DIR=/runner/data
      - RUNNER_SCOPE=org
      - ORG_NAME=binary-braids
      - RUN_AS_ROOT=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github-runner-data:/runner/data
      - /tmp/runner:/tmp/runner
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro