name: emulatorjs

networks:
  proxy:
    external: true

volumes:
  emulatorjs-data:
    name: emulatorjs-data

services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:amd64-1.9.2
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - emulatorjs-data:/config
      - emulatorjs-data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emulatorjs.rule=Host(`emulatorjs.binarybraids.com`)"
      - "traefik.http.routers.emulatorjs.entrypoints=https"
      - "traefik.http.routers.emulatorjs.tls=true"
      - "traefik.http.routers.emulatorjs.service=emulatorjs"
      - "traefik.http.services.emulatorjs.loadbalancer.server.port=80"
      - "traefik.http.routers.emulatorjs-config.rule=Host(`emulatorjs-config.binarybraids.com`)"
      - "traefik.http.routers.emulatorjs-config.entrypoints=https"
      - "traefik.http.routers.emulatorjs-config.tls=true"
      - "traefik.http.routers.emulatorjs-config.service=emulatorjs-config"
      - "traefik.http.services.emulatorjs-config.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"