name: traefik

volumes:
  traefik:
    name: traefik
  acme:
    name: acme

services:
  traefik:
    image: "traefik:latest@sha256:664bb8415fddadb71c2682b329c427d12c7d53593171665f2b7b6ff924509bc1"
    container_name: "traefik"
    environment:
      - "CF_API_EMAIL=${CLOUDFLARE_EMAIL}"
      - "CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}"
      - "TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/acme/acme.json"
    ports:  
      - "80:80"
      - "443:443"  
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "traefik:/var/log/traefik"
      - "acme:/acme"
    configs:
      - source: traefik.yaml
        target: /etc/traefik/traefik.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`pi-traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN_NAME}"

configs:
  traefik.yaml:
    content: |
      api:
        dashboard: true

      entryPoints:
        web:
          address: ":80"
          http:
            redirections:
              entryPoint:
                to: websecure
                scheme: https

        websecure:
          address: ":443"

      providers:
        docker:
          endpoint: "unix:///var/run/docker.sock"
          exposedByDefault: false


      certificatesResolvers:
        letsencrypt:
          acme:
            email: ${CLOUDFLARE_EMAIL}
            storage: /acme/acme.json
            dnsChallenge:
              provider: cloudflare

networks:
  proxy:
    name: proxy